import { Inter } from "next/font/google";
import ReactQueryProvider from "@/shared/providers/ReactQueryProvider";
import "../styles/globals.scss";
import GalaxyRenderer from "@/shared/providers/GalaxyProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <GalaxyRenderer />
                <ReactQueryProvider>{children}</ReactQueryProvider>
            </body>
        </html>
    );
}
