import { Inter } from "next/font/google";
import ReactQueryProvider from "@/shared/providers/ReactQueryProvider";
import "../styles/globals.scss";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <Theme>
                    <ReactQueryProvider>{children}</ReactQueryProvider>
                </Theme>
            </body>
        </html>
    );
}
